### PR TITLE
Feature/sim 2229/add m5 calc

### PR DESCRIPTION
**Pull request by yoachim**

### CODE REVIEW

**Comment by ivezic** [comment]
Which values are hard coded? Who is supposed to use this piece of code?
How shall we ensure that hard coded values stay up to date and consistent
with the SysEng controlled "best system estimates"?

**Comment by yoachim** [comment]
Because the SysEng code is not an eups package it does not get distributed with the rest of the sims install, thus we have to pull the m5 relevant values over manually. I think @rhiannonlynne argued that we didn't want values changing unexpectedly, so it would make more sense to separate the SysEng and sims values.

**Comment by rhiannonlynne** [comment]
I think we have to add code in syseng-throughputs that can update the code here (best if it's an easily separable piece, maybe a dictionary?), then make it a requirement that when syseng is updated, that update code is run and updated here.

**Comment by yoachim** [comment]
Sure, would be pretty easy to dump the syseng values to a dict that gets read in here. I'm not positive I have privileges on the syseng repo, so I'm going to merge this and make updating the read in of the values a new branch.

**Comment by ivezic** [comment]
There are a few easy additions that would decrease likelihood of someone using an 
obsolete version:
- in the code comment that refers to "v1.2 of the SYSENG_THROUGHPUTS repo",
  also add the date when that version was tagged
- add an option to photo_m5 to print or return that date and the repo version
- (perhaps) check an appropriate file in syseng repo which would tell you that 
  the syseng "latest and greatest" values were updated, and if so issue a warning
  (or perhaps error?) 

Is this one place in photo_m5 *the only* place in that repo where those values 
are specified? If not, it should be internally fixed. 

PS
Should we make SysEng code use eups machinery?

**Comment by danielsf** [comment]
I'm not sure if these are syseng-generated values, but we also hard-code some LSST parameters (readnoise, gain, effective area) here:

https://github.com/lsst/sims_photUtils/blob/master/python/lsst/sims/photUtils/PhotometricParameters.py

**Comment by ivezic** [comment]
OK, thanks. I would strongly suggest to completely remove all such hard coded 
values from the actual code and instead read them from an input ("configuration" 
file). Eventually you can start machine-producing that file using a piece of code 
in SysEng repo, as proposed by Lynne. The current values can be moved to a 
default (but fully documented) input file which lives in sims_utils repo. This way
there is one and only one place/file that we need to worry about.

**Pull request merged**
